port: 8080
map-artifacts: true
debian-repo: /usr/share/maven-repo
maven-proxy-cache: local-maven-proxy-cache
remotes:
  - https://repo.maven.apache.org/maven2/
  - https://dl.google.com/dl/android/maven2/
  - https://repo.gradle.org/gradle/repo/
  - https://plugins.gradle.org/m2/
  - https://repo.gradle.org/gradle/public/
  - https://repo.gradle.org/gradle/javascript-public/
  - https://maven.pkg.jetbrains.space/kotlin/p/kotlin/kotlin-dependencies/
  - https://maven.repository.redhat.com/ga/
build:
  type: maven
  helper-path: /usr/share/maven-repo # maven-repo-helper lives here
  build-executable: /usr/share/maven/bin/mvn
  workingDirectory: /home/vladimirp/git/make-oss-25/flink/
  command:
    - package
    - -DskipTests
    - -Djdk17
    - -Pjava17-target
