name: dj-package-list
base: core24
version: '0.1'
summary: A list of artifact to Ubuntu package mappings for Java
description: |
  This snap provides a view of Java artifacts in Plucky.

  The dj-package-list command starts an HTTP server on port 11111 and opens a browser.

  Run the following command to list the Java package build dependencies for the project in <dir>:
  java -jar /snap/dj-package-list/current/jar/checkdepends-0.0.1-SNAPSHOT.jar maven-check <dir> <maven-goal> [maven args]

grade: devel
confinement: strict

platforms:
  amd64:

apps:
  dj-package-list:
    command: bin/java -jar $SNAP/jar/checkdepends-0.0.1-SNAPSHOT.jar
    plugs:
      - network
      - network-bind
      - desktop

parts:
  browser:
    plugin: maven
    build-packages:
      - default-jdk
      - maven
    stage-packages:
      - default-jdk
    source: check-depends
